### ISSUE TITLE
Multiple customizations

### ISSUE THREAD

**Issue by heiyutian** [srgl/ua-smart-switcher#8]
I need a lot of UA that are not in the list, there is only one customization, I need multiple saved and can switch.

**Comment by srgl** [comment]
May I know how many custom ua strings you need? Maybe it is better to add them to the list (if they are browsers)?

**Comment by heiyutian** [comment]
> May I know how many custom ua strings you need? Maybe it is better to add them to the list (if they are browsers)?

No, many services in our country need the corresponding appUA to open, non-ordinary browser UA, many are my own temporary crawl

**Comment by srgl** [comment]
Got this and I think this will be useful. Expect to see this feature before or on the next week.

**Comment by heiyutian** [comment]
> Got this and I think this will be useful. Expect to see this feature before or on the next week.

Discover a problem, the default ua has problems, unable to access the website that opens the CloudFlare 5 Seconds security check, there will be repeated refreshing web pages, only part of the UA has this phenomenon, such as Chrome90 and Firefox88

**Comment by srgl** [comment]
@heiyutian could you provide example url?

**Comment by heiyutian** [comment]
> @heiyutian could you provide example url?

View your email

**Comment by srgl** [comment]
@heiyutian Can't reproduce it with the latest version 1.4.0 and Windows + Chrome 90
Please check it.

**Comment by heiyutian** [comment]
> @heiyutian Can't reproduce it with the latest version 1.4.0 and Windows + Chrome 90
> Please check it.

I sent you a new email.
At the same time, a new issue is reported, and UA is detected on this website. UA is the original
https://webbrowsertools.com/useragent/

**Comment by srgl** [comment]
> Updated to the latest version, At the same time, a new issue is reported, and UA is detected on this website. UA is the original
https://webbrowsertools.com/useragent/
This web site is using aggressive techniques to get original user agent. For now, I have no ideas how to bypass it.

Also, what chrome version and user agent you using to access the sites you sent me? I still can't reproduce CF issue.

**Comment by heiyutian** [comment]
> > Updated to the latest version, At the same time, a new issue is reported, and UA is detected on this website. UA is the original
> > https://webbrowsertools.com/useragent/
> 
> This web site is using aggressive techniques to get original user agent. For now, I have no ideas how to bypass it.
> 
> Also, what chrome version and user agent you using to access the sites you sent me? I still can't reproduce CF issue.

Send you a video
I close other extension tests,
There are two chrome versions on my computer
This cycle will occur in both cases

**Comment by srgl** [comment]
@heiyutian I was able to reproduce the issue with Chrome 85. Unfortunately, I don't know what the problem is, so please update your chrome to latest version - Chrome 90 doesn't have this issue.

**Comment by heiyutian** [comment]
> @heiyutian I was able to reproduce the issue with Chrome 85. Unfortunately, I don't know what the problem is, so please update your chrome to latest version - Chrome 90 doesn't have this issue.

I have some extensions and scripts that can only be useful in the old version, so I will use it for a long time, 85 and 77.

**Comment by srgl** [comment]
@heiyutian I understand. Unfortunately, there is no error messages in the console and no clue why cloudflare does infinite redirection. If you know any extension which has no such issue with old chrome then send it to me and I will look the code and try to make a fix.

**Comment by heiyutian** [comment]
> @heiyutian I understand. Unfortunately, there is no error messages in the console and no clue why cloudflare does infinite redirection. If you know any extension which has no such issue with old chrome then send it to me and I will look the code and try to make a fix.

Not all UA will appear, I didn't find the extension that can be bypassed using the 90 version.

However, I found a expansion that can change UA on this website, this extension is too bloated, the same in the CF loop
https://webbrowsertools.com/useragent/
https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg

**Comment by heiyutian** [comment]
> @heiyutian I understand. Unfortunately, there is no error messages in the console and no clue why cloudflare does infinite redirection. If you know any extension which has no such issue with old chrome then send it to me and I will look the code and try to make a fix.

This extension is already great, and if it's hard to implement, you don't have to force it.

**Comment by srgl** [comment]
> However, I found a expansion that can change UA on this website, this extension is too bloated, the same in the CF loop
https://webbrowsertools.com/useragent/
https://chrome.google.com/webstore/detail/user-agent-switcher-and-m/bhchdcejhohfmigjafbampogmaanbfkg

For me it works only sometimes, maybe 1 time out of 10, try to refresh page multiple times.
I don't believe there is an extension which can bypass all the aggressive checks - due to how chrome extensions work currently.

**Comment by heiyutian** [comment]
Ok, just let it be
